version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    links:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo
    ports:
      - "8001:27017"
    volumes:
      - ./mongodb-data:/data/db